
function(add_basic_warnings target)
    if (${CMAKE_CXX_COMPILER_ID} STREQUAL "Clang")
        target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic -Wshadow)
    elseif (${CMAKE_CXX_COMPILER_ID} STREQUAL "GNU")
        target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic -Wshadow)
    elseif (${CMAKE_CXX_COMPILER_ID} STREQUAL "Intel")
        message(WARNING "Don't know intel compiler warning flags")
    elseif (${CMAKE_CXX_COMPILER_ID} STREQUAL "MSVC")
        target_compile_options(${target} PRIVATE /W4)
    endif()
endfunction()
